const lang = {
    english:{
        
         gptSearchPlaceholder: "What would you like to watch today?" ,
         AISearchBtn : "AI Search" ,
         doSignIn  : "Sign In",
         doSignOut : "Sign Out",
         doSignUp :  "Sign Up" ,
         EmailPlaceholder : "Email Address" ,
         OrText : "OR" ,
         PasswordPlaceholder : "Password" ,
         UseSignInCode : "Use a sign-in code" ,
         ForgotPassword : "Forgot password?" ,
         NewToNetflix : "New to Netflix?" ,
         SignInNow : "Sign In Now"  ,
         SignUpNow : "Sign Up Now" ,
         FullNamePlaceholder : "Full Name" ,
         AlreadyRegistered : "Already Registered?" ,
         SignInWithMobile : "Sign In with Mobile" ,
         btnMoreInfo : "More Info" ,
         btnPlay : "Play" ,
         TrendingMovie : "Trending" ,
        
    },
    hindi:{
        
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?" ,
        AISearchBtn : "AI द्वारा खोज" ,
        doSignIn  :  "साइन इन" ,
        doSignOut : "साइन आउट",
        doSignUp :  "साइन अप" ,
        EmailPlaceholder : "ईमेल एड्रेस" ,
        OrText : "या" ,
        PasswordPlaceholder : "पासवर्ड" ,
        UseSignInCode : "साइन-इन कोड का इस्तेमाल करें" ,
        ForgotPassword : "पासवर्ड भूल गए?" ,
        NewToNetflix : "Netflix पर नए हैं?" ,
        SignInNow : "अभी साइन इन करें"  ,
        SignUpNow : "अभी साइन अप करें" ,
        FullNamePlaceholder : "पूरा नाम" ,
        AlreadyRegistered : "पहले से ही पंजीकृत?" ,
        SignInWithMobile : "मोबाइल से साइन इन करें" ,
        btnMoreInfo : "अधिक जानकारी" ,
        btnPlay : "चलाएं" ,
        TrendingMovie : "ट्रेंडिंग" ,

    },
    bengali:{
        
        gptSearchPlaceholder:"আপনি আজ কি দেখতে চান?" ,
        AISearchBtn : "AI দ্বারা খোঁজ" ,
        doSignIn : "সাইন-ইন" ,
        doSignOut : "সাইন আউট",
        doSignUp :  "সাইন আপ" ,
        EmailPlaceholder : "ইমেল" ,
        OrText : "অথবা" ,
        PasswordPlaceholder : "পাসওয়ার্ড" ,
        UseSignInCode : "সাইন-ইন কোড ব্যবহার করুন" ,
        ForgotPassword : "পাসওয়ার্ড ভুলে গেছেন?" ,
        NewToNetflix : "Netflix এ নতুন?" ,
        SignInNow : "এখনই সাইন ইন করুন"  ,
        SignUpNow : "এখনই সাইন আপ করুন" ,
        FullNamePlaceholder : "পুরো নাম" ,
        AlreadyRegistered : "ইতিমধ্যে রেজিষ্ট্রার্ড?" ,
        SignInWithMobile : "মোবাইল থেকে সাইন ইন করুন" ,
        btnMoreInfo : "আরও তথ্য" ,
        btnPlay : "চালান" ,
        TrendingMovie : "ট্রেন্ডিং" ,
    },
    spanish:{
        search:"buscar",
        gptSearchPlaceholder:"¿Qué te gustaría ver hoy?" ,
        AISearchBtn : "Buscar con IA",
        doSignIn : "Registrarse" ,
        doSignOut  : "cerrar sesión" ,
        doSignUp :  "Inscribirse" ,
        EmailPlaceholder : "Correo electrónico" ,
        OrText : "O" ,
        PasswordPlaceholder : "Contraseña" ,
        UseSignInCode : "Utilice el código de inicio de sesión" ,
        ForgotPassword : "¿Has olvidado tu contraseña?" ,
        NewToNetflix : "¿Nuevo en Netflix?" ,
        SignInNow : "Iniciar sesión ahora"  ,
        SignUpNow : "Regístrate ahora" ,
        FullNamePlaceholder : "Nombre completo" ,
        AlreadyRegistered : "¿Ya estás registrado?" ,
        SignInWithMobile : "Iniciar sesión con el móvil" ,
        btnMoreInfo : "Más información" , 
        btnPlay : "Reproducir" ,
        TrendingMovie : "de tendencia" ,
    }
}

export default lang;